Library/Controllers/BranchController.cs
using Library.Database.Entities.Identity;
using Library.Domain.Attributes;
using Library.Models.Branch;
using Library.Services.Interfaces;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Library.Controllers
{
    [AuthorizeRoles(Role.AdminRole, Role.LibrarianRole, Role.ReaderRole)]
    public class BranchController : Controller
    {
        public readonly IBranchService _branch;

        public async Task<ActionResult> Index()
        {
            var branchModels = await Task.WhenAll(_branch.GetAll()
                .Select(async x => new BranchDetailModel
                {
                    Id = x.Id,
                    BranchName = x.Name,
                    NumberOfAssets = await _branch.GetAssetCountAsync(x.Id),
                    NumberOfPatrons = await _branch.GetPatronCountAsync(x.Id),
                    IsOpen = _branch.IsBranchOpen(x.Id)
                }).ToList());

            var model = new BranchIndexModel
            {
                Branches = branchModels
            };

            return View(model);
        }

        public async Task<ActionResult> Detail(long id)
        {
            var branch = await _branch.GetAsync(id);
            var model = new BranchDetailModel
            {
                BranchName = branch.Name,
                Description = branch.Description,
                Address = branch.Address,
                Telephone = branch.Telephone,
                BranchOpenedDate = branch.OpenDate.ToString("yyyy-MM-dd"),
                NumberOfPatrons = await _branch.GetPatronCountAsync(id),
                NumberOfAssets = await _branch.GetAssetCountAsync(id),
                TotalAssetValue = _branch.GetAssetsValue(id),
                ImageUrl = branch.ImageUrl,
                HoursOpen = _branch.GetBranchHours(id)
            };

            return View(model);
        }
    }
}

Library/Controllers/CatalogController.cs
using Library.Database.Entities.Identity;
using Library.Domain.Attributes;
using Library.Extensions;
using Library.Models.Catalog;
using Library.Models.Checkout;
using Library.Models.Repository.Interfaces;
using Library.Services.Interfaces;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Library.Controllers
{
    [AuthorizeRoles(Role.AdminRole, Role.LibrarianRole, Role.ReaderRole)]
    public class CatalogController : Controller
    {
        public ILibraryAssetService _asset;
        public ICheckoutService _checkouts;

        [HttpGet]
        [HttpPost]
        public async Task<ActionResult> Index()
        {
            var assetModels = _asset.GetAll();

            var listingResult = await Task.WhenAll(assetModels
                .Select(async x => new AssetIndexListingModel
                {
                    Id = x.Id,
                    ImageUrl = x.ImageUrl,
                    AuthorOrDirector = await _asset.GetAuthorOrDirectorAsync(x.Id),
                    DeweyCallNumber = await _asset.GetDeweyIndexAsync(x.Id),
                    Title = x.Name,
                    Type = await _asset.GetTypeAsync(x.Id),
                    Description = await _asset.GetDescriptionAsync(x.Id),
                    Publisher = await _asset.GetPublisherAsync(x.Id),
                }));

            var model = new AssetIndexModel()
            {
                Assets = listingResult
            };

            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> Detail(long id)
        {
            var asset = await _asset.GetByIdAsync(id);

            var currentHolds = await Task.WhenAll(_checkouts.GetCurrentHolds(id)
                .Select(async x => new AssetHoldModel
                {
                    HoldPlaced = await _checkouts.GetCurrentHoldPlacedAsync(x.Id),
                    PatronName = await _checkouts.GetCurrentHoldPatronNameAsync(x.Id)
                }));

            var model = new AssetDetailModel
            {
                AssetId = id,
                Title = asset.Name,
                Description = asset.Description?.GetRandomString(),
                Year = asset.Year,
                Publisher = await _asset.GetPublisherAsync(id),
                Status = asset.Status.Name,
                ImageUrl = asset.ImageUrl,
                AuthorOrDirector = _asset.GetAuthorOrDirector(id),
                CurentLocation = _asset.GetCurrentLocation(id).Name,
                DeweyCallNumber = _asset.GetDeweyIndex(id),
                CheckoutHistory = _checkouts.GetCheckoutHistory(id),
                LatestCheckout = await _checkouts.GetLatestCheckout(id),
                PatronName = await _checkouts.GetCurrentCheckoutPatronAsync(id),
                CurrentHolds = currentHolds
            };

            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> Checkout(long id)
        {
            var asset = await _asset.GetByIdAsync(id);

            var model = new CheckoutModel
            {
                AssetId = id,
                ImageUrl = asset.ImageUrl,
                Title = asset.Name,
                LibraryCardId = "",
                IsCheckedOut = await _checkouts.IsCheckedOutAsync(id)
            };

            return View(model);
        }

        [HttpGet]
        public ActionResult CheckIn(long id)
        {
            _checkouts.CheckInTimeAsync(id);
            return RedirectToAction("Detail", new { id });
        }

        [HttpGet]
        public async Task<ActionResult> Hold(long id)
        {
            var asset = await _asset.GetByIdAsync(id);

            var model = new CheckoutModel
            {
                AssetId = id,
                ImageUrl = asset.ImageUrl,
                Title = asset.Name,
                LibraryCardId = "",
                IsCheckedOut = await _checkouts.IsCheckedOutAsync(id),
                HoldCount = _checkouts.GetCurrentHolds(id).Count()
            };

            return View(model);
        }

        public ActionResult MarkFind(long id)
        {
            _checkouts.MarkFound(id);
            return RedirectToAction("DEtail", new { id });
        }

        public ActionResult MarkLost(long id)
        {
            _checkouts.MarkLost(id);
            return RedirectToAction("Detail", new { id });
        }

        [HttpPost]
        public ActionResult PlaceCheckout(long id, long libraryCardId)
        {
            _checkouts.CheckOutTimeAsync(id, libraryCardId);

            return RedirectToAction("Detail", new { id });
        }

        [HttpPost]
        public ActionResult PlaceHold(long id, long libraryCardId)
        {
            _checkouts.PlaceHoldAsync(id, libraryCardId);

            return RedirectToAction("Detail", new { id });
        }
    }
}

Library/Controllers/PatronController.cs
using Library.Database.Entities.Identity;
using Library.Domain.Attributes;
using Library.Models.User;
using Library.Services.Interfaces;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Library.Controllers
{
    [AuthorizeRoles(Role.AdminRole, Role.LibrarianRole, Role.ReaderRole)]
    public class PatronController : Controller
    {
        public IPatronService _patron;
        public ActionResult Index()
        {
            var allPatrons = _patron.GetAll();

            var patronModel = allPatrons.Select(x => new PatronDetailModel
            {
                Id = x.Id,
                LastName = x.LastName ?? "No First Name Provided",
                FirstName = x.FirstName ?? "No Last Name Provided",
                LibraryCardId = x.LibraryCard?.Id,
                HomeLibrary = x.LibraryBranch?.Name
            });

            var model = new PatronIndexModel
            {
                Patrons = patronModel
            };

            return View(model);
        }

        public async Task<ActionResult> Detail(int id)
        {
            var patron = await _patron.GetAsync(id);

            var assets = await _patron.GetCheckoutsAsync(id);

            var model = new PatronDetailModel
            {
                Id = patron.Id,
                LastName = patron.LastName ?? "No Last Name Provided",
                FirstName = patron.FirstName ?? "No First Name Provided",
                HomeLibrary = patron.LibraryBranch?.Name ?? "No Home Library",
                MemberSince = patron.LibraryCard?.Created,
                LibraryCardId = patron.LibraryCard?.Id,
                Telephone = string.IsNullOrEmpty(patron.PhoneNumber) ? "No Telephone Number Provided" : patron.PhoneNumber,
                AssetsCheckedOut = assets.ToList(),
                CheckoutHistory = _patron.GetCheckoutHistory(id),
                Holds = _patron.GetHolds(id)
            };
            return View(model);
        }
    }
}

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css" />
    <link href=”//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css” rel=”stylesheet”>
    <link href="https://fonts.googleapis.com/css?family=Coda" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/Site.css" />
</head>

<body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="custom-header mdl-layout__header mdl-layout__header--waterfall">
            <div class="mdl-layout__header-row">
                <span class="mdl-layout-title logo"><a href="/">Start page</a></span>
                <div class="mdl-layout-spacer"></div>
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a class="mdl-navigation__link" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="mdl-navigation__link" asp-controller="Catalog" asp-action="Index">Catalog</a>
                    <a class="mdl-navigation__link" asp-controller="Patron" asp-action="Index">Patrons</a>
                    <a class="mdl-navigation__link" asp-controller="Branch" asp-action="Index">Branches</a>
                </nav>
            </div>
        </header>
        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title"></span>
            <nav class="mdl-navigation">
                <a class="mdl-navigation__link" asp-controller="Home" asp-action="Index">Home</a>
                <a class="mdl-navigation__link" asp-controller="Catalog" asp-action="Index">Catalog</a>
                <a class="mdl-navigation__link" asp-controller="Patron" asp-action="Index">Patrons</a>
                <a class="mdl-navigation__link" asp-controller="Branch" asp-action="Index">Branches</a>
            </nav>
        </div>
        <div class="page-content">
            @RenderBody()
        </div>
    </div>

    @RenderSection("Styles", required: false)
    @RenderSection("Scripts", required: false)
    <script src="https://use.fontawesome.com/6110b02b27.js"></script>
</body>
</html>